name: EffectiveMobile CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest
          pip install playwright
          playwright install

      - name: Run tests with Allure results
        run: pytest --alluredir=allure-results

      - name: Download Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.2/allure-2.27.2.zip
          unzip allure-2.27.2.zip -d $HOME/allure
          export PATH=$HOME/allure/allure-2.27.2/bin:$PATH
          allure --version

      - name: Generate Allure report
        run: |
          export PATH=$HOME/allure/allure-2.27.2/bin:$PATH
          allure generate allure-results -o allure-report --clean

      - name: Deploy Allure report to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
